[package]
name = "package-04-actix-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"

[dependencies.mongodb]
version = "3.1.0"
